{% set name = "cmaes" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 580f5e40f25f57153deaf821b2b51b50ed6b598963af3966a50aa42b40609dba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - python >=3.7

test:
  imports:
    - cmaes

about:
  home: https://github.com/CyberAgentAILab/cmaes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Lightweight Covariance Matrix Adaptation Evolution Strategy (CMA-ES) implementation for Python 3.
  dev_url: https://github.com/CyberAgentAILab/cmaes

extra:
  recipe-maintainers:
    - nomuramasahir0
    - c-bata
