{% set name = "cmaes" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 48afc70df027114739872b50489ae6b32461c307b92d084a63c7090a9742faf9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - python >=3.7

test:
  imports:
    - cmaes

about:
  home: https://github.com/CyberAgentAILab/cmaes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Lightweight Covariance Matrix Adaptation Evolution Strategy (CMA-ES) implementation for Python 3.
  dev_url: https://github.com/CyberAgentAILab/cmaes

extra:
  recipe-maintainers:
    - nomuramasahir0
    - c-bata
