{% set name = "cmaes" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f56a9e8dd769ffd23ac2ad651979bdb6ca8846de60d97d03fe5ad8456c56c79

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - cmaes

about:
  home: https://github.com/CyberAgentAILab/cmaes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Lightweight Covariance Matrix Adaptation Evolution Strategy (CMA-ES) implementation for Python 3.
  dev_url: https://github.com/CyberAgentAILab/cmaes

extra:
  recipe-maintainers:
    - ciela
    - NaokiHamada
    - ha-mano
    - nomuramasahir0
    - c-bata
