{% set name = "cmaes" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6aab41eee2f38bf917560a7e7d1ba0060632cd44cdf7ac2a10704da994624182

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - cmaes

about:
  home: https://github.com/CyberAgentAILab/cmaes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Lightweight Covariance Matrix Adaptation Evolution Strategy (CMA-ES) implementation for Python 3.
  dev_url: https://github.com/CyberAgentAILab/cmaes

extra:
  recipe-maintainers:
    - ha-mano
    - nomuramasahir0
    - c-bata
